### ISSUE TITLE
Error on second function

### ISSUE THREAD

**Issue by CaptainAmerica3** [pixelbubble/ProtOSINT#3]
The other functions of the program work well. I keep getting the following error below. 

I'm trying some combinaison: 78
===============================
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/6158DF7C-BEB5-4BDE-AE23-B625252F053F/Documents/osnit.py", line 216, in checkGeneratedProtonAccounts
    timestamp = int(re.search(regexPattern1, bodyResponse).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/6158DF7C-BEB5-4BDE-AE23-B625252F053F/Documents/osnit.py", line 221, in checkGeneratedProtonAccounts
    timestamp = int(re.search(regexPattern2, bodyResponse).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/6158DF7C-BEB5-4BDE-AE23-B625252F053F/Documents/osnit.py", line 264, in <module>
    main()
  File "/var/mobile/Containers/Data/Application/6158DF7C-BEB5-4BDE-AE23-B625252F053F/Documents/osnit.py", line 259, in main
    checkGeneratedProtonAccounts()
  File "/var/mobile/Containers/Data/Application/6158DF7C-BEB5-4BDE-AE23-B625252F053F/Documents/osnit.py", line 225, in checkGeneratedProtonAccounts
    timestamp = int(re.search(regexPattern3, bodyResponse).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by pixelbubble** [comment]
Problem solved: https://github.com/pixelbubble/ProtOSINT/pull/4
